version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - JWT_SECRET=bb#123$joao
      - DB_NAME=musicstream
    depends_on:
      - mongodb
    networks:
      - music-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - music-network

volumes:
  mongodb_data:

networks:
  music-network:
    driver: bridge 