version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - JWT_SECRET=bb#123$joao
      - DB_NAME=musicstream
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - BUCKET_NAME=music-bucket
    volumes:
      - ./storage/music:/app/storage/music
    depends_on:
      - mongodb
      - minio
      - minio-init
    networks:
      - music-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - music-network

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - music-network

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5 &&
      mc alias set myminio http://minio:9000 minioadmin minioadmin &&
      mc mb --ignore-existing myminio/music-bucket
      "
    networks:
      - music-network

volumes:
  mongodb_data:
  minio_data:

networks:
  music-network:
    driver: bridge 